### ISSUE TITLE
[아이템 7] 타입이 값들의 집합이라고 생각하기

### ISSUE THREAD

**Issue by han-kimm** [code-itch/effective-typescript#11]

**Comment by Ssong-Q** [comment]
> p.37 5번째줄

타입들을 집합으로 비유했을 때, 아무 값도 포함하지 않는 never타입은 공집합이라고 할 수 있다고 책에 적혀있습니다. 
혹시 never 타입이 필요한 이유와 쓰이는 상황은 어떤 것들이 있을지 설명 가능하실까요?

**Comment by han-kimm** [comment]
작성중입니다.....!

**Never의 쓰임 1. 함수 호출을 막기**
never타입에 값이 할당이 안되는 걸 이용하면 특정 메소드를 오버라이딩, 즉 덮어쓰기를 해서 함수 파라미터의 타입을 never로 바꾸어 readonly 객체로 만들 수 있습니다.

**Never의 쓰임 2. A | B 의 유니온 타입에서 A타입 또는 B타입으로 가드하기**
never은 공집합이므로 유니온 타입에서 항상 병합 된다는 걸 이용합니다. never | string 은 string이죠.

```
type VariantA = {
    a: string
    b?: never
}

type VariantB = {
    b: number
    a?: never
}

declare function fn(arg: VariantA | VariantB): void


const input = {a: 'foo', b: 123 }
fn(input) // 타입스크립트 에러, b는 undefined | never 에서 undefined 입니다.
```

Exclude의 경우에서는 유니온 타입에서 |로 연결된 각 타입들을 집합의 원소라고 생각하시면 좋을것 같습니다. string | Date 유니온의 경우에는 string 원소는 string | number 집합의 원소가 될 수 있기 때문에 never가 됩니다.

**Comment by han-kimm** [comment]
이야기를 시작하기 앞서서, &의 교집합과 |의 합집합에 대한 오해를 바로잡고 싶습니다.
```
type A = { name: string }
type B = { age: number }

type C = A & B

const c : C = {name: '하늘'}
// '{ name: "하늘"; }' 형식은 'C' 형식에 할당할 수 없습니다.
  'age' 속성이 '{ name: "하늘"; }' 형식에 없지만 'B' 형식에서 필수입니다.

const c : C = {name: '하늘', age: 27}
// OK
```
타입스크립트에서 A & B는 A와 B의 공통 속성을 갖는 타입을 의미하는 것이 아닙니다. A이자 B인 타입을 의미합니다. 즉, A & B 를 오해하면 never타입처럼 추론되는데, 실제 타입스크립트는 A이자 B이므로 두 타입의 속성을 모두 갖는 타입을 의미합니다. 이와 같이 A | B는 합집합으로 두 타입의 모든 속성을 갖는 타입으로 오해할 수 있습니다. 타입스크립트에서는 A 또는 B를 의미하며 A일때는 name 속성, B일때는 age 속성을 가지므로 둘 중 하나의 속성만 가지면 OK가 됩니다.

이어서 Exclude에 대해서 정의에 따라 설명을 하자면 `type Exclude<T, U> = T extends U ? never : T;`와 `type S = Exclude<string|Date, string|number>;`에서 제네릭 T에 해당하는  string | Date 는 string 또는 Date입니다. T가 string일 경우에는 제네릭 U의 string | number 집합의 부분집합이 되므로 never, T가 Date인 경우에는 부분집합이 되지 않으므로 Date가 됩니다. 따라서 |는 "합친다"는 개념보다는 "또는"으로 보면 이해가 더 빠를 것 같습니다.

수학적으로 이해하고 싶으시다면 집합과 명제 단원을 공부해보시면 좋을 것 같아요. 아니면 철학에서 언어 명제와 집합에 대해서 알아보면 이해에 도움이 될 것 같습니다.

---

**Never의 쓰임 1. 함수 호출을 막기**
never타입에 값이 할당이 안되는 걸 이용하면 특정 메소드를 오버라이딩, 즉 덮어쓰기를 해서 함수 파라미터의 타입을 never로 바꾸어 readonly 객체로 만들 수 있습니다.

**Never의 쓰임 2. A | B 의 유니온 타입에서 A타입 또는 B타입으로 가드하기**
never은 공집합이므로 유니온 타입에서 항상 병합 된다는 걸 이용합니다. never | string 은 string이죠.
이것은 Exclude의 정의에서 응용된 것과 같습니다.  `type Exclude<T, U> = T extends U ? never : T;`에서, T가 U의 부분집합에 해당하면 never로 타입변환을 하여 공집합, 즉 소거해버리는 것이죠.

```
type VariantA = {
    a: string
    b?: never
}

type VariantB = {
    b: number
    a?: never
}

declare function fn(arg: VariantA | VariantB): void


const input = {a: 'foo', b: 123 }
fn(input) // 타입스크립트 에러, b는 undefined | never 에서 undefined 입니다.

**Comment by kses1010** [comment]
> p44 코드
```ts
interface Point {  
  x: number;  
  y: number;  
}  
type PointKeys = keyof Point; // 타입은 "x | "y"  
function sortBy<K extends keyof T, T>(vals: T[], key: K): T[] {   // 컴파일 에러
  
}  
  
const pts: Point[] = [{x: 1, y: 1}, {x: 2, y: 0}];  
sortBy(pts, 'x');  
sortBy(pts, 'y');  
sortBy(pts, Math.random() < 0.5 ? 'x' : 'y');  
sortBy(pts, 'z'); // 타입 에러
```
<img width="757" alt="image" src="https://github.com/code-itch/effective-typescript/assets/49144662/da1e2322-4750-42f5-9041-e7d842f8b0b0">
여기에서 발생하는 함수의 리턴값이 왜 타입에러가 날까요?

**Comment by han-kimm** [comment]
아무것도 리턴하고 있지 않아서, 리턴타입인 T[]에 void가 할당될 수 없어서?

**Comment by kses1010** [comment]
@han-kimm 
책에서 return값이 없어서 없어도 잘 동작하는줄 알았네요

**Comment by BeMatthewsong** [comment]
@Ssong-Q  
never 타입은 불가능을 의미하는 타입입니다. 
하늘님께서 좋은 사용예시를 알려주셔서 거기에 제가 알고 있는 예시를 덧붙여서 설명드리자면 아래 내용과 같습니다.
### 1. 무한루프
무한 루프는 아무런 값도 반환하지 않기 때문에 반환값 타입에 never를 명시합니다. 
```ts
function func(): never {
  while (true) {}
}
```
### 2. 오류 발생
의도적으로 오류를 발생시키는 함수도 아무런 값을 반환하지 않아 반환값 타입에 never를 명시합니다.
```ts
function func(): never {
  throw new Error();
}
```
### 3. any를 담을 수 없게 하기  (값을 포함할 수 없는 빈 타입 - never)
변수의 타입을 never로 정의하면, any를 포함해 그 어떠한 타입의 값도 이 변수에 담을 수 없게 됩니다.
