### ISSUE TITLE
[아이템 8] 타입 공간과 값 공간의 심벌 구분하기

### ISSUE THREAD

**Issue by han-kimm** [code-itch/effective-typescript#12]

**Comment by BeMatthewsong** [comment]
심벌이라는 말이 어색한데 이해하기 좋은 말로 치환할 수 있을까요?

**Comment by kses1010** [comment]
@BeMatthewsong
아무래도 Symbol이 실제 자바스크립트에 있는 키워드다보니 애매하긴 하네용

**Comment by han-kimm** [comment]
@BeMatthewsong 
자바스크립트에서는 심볼을 보통 속성을 정의할 때 고유한 값으로 쓰는데
전역변수는 window 객체의 속성으로 정의되어서 심볼이라는 용어를 사용하고 있는 게 아닌가 싶습니다.

**Comment by gw-lim** [comment]
@BeMatthewsong 
두 공간에서 사용되는 키워드들이 상이하기에 정확하게 치환할 수는 없겠으나, 단지 이해만을 위해 사용한다면 `선언명`라고 생각하셔도 될 것 같습니다!
