### ISSUE TITLE
[아이템 9] 타입 단언보다는 타입 선언을 이용하기

### ISSUE THREAD

**Issue by han-kimm** [code-itch/effective-typescript#13]

**Comment by BeMatthewsong** [comment]
> p.55 그러나 함수 호출 체이닝이 연속되는 곳에서 체이닝 시작에서부터 명명된 타입을 가져야 한다.

이 말에서 체이닝에 들어가는 콜백함수에서의 매개변수의 타입을 명시하라는 의미로 이해하면 되나요?

**Comment by han-kimm** [comment]
넵~ 화살표 함수에서 타입 추론이 좀 더 넓은 범위의 집합으로 추론될 때가 있어서,
명확하게 정의된 타입 또는 리터럴을 사용하여 범위를 한정시켜주는 게 타입 추론에 도움이 된다는 의미인 것 같습니다

**Comment by qooktree1** [comment]
> > p.55 그러나 함수 호출 체이닝이 연속되는 곳에서 체이닝 시작에서부터 명명된 타입을 가져야 한다.
> 
> 이 말에서 체이닝에 들어가는 콜백함수에서의 매개변수의 타입을 명시하라는 의미로 이해하면 되나요?

하늘님 답변 감사합니다! 콜백함수 내에서의 매개변수 타입 명시하는게 맞습니다!
