### ISSUE TITLE
[아이템 1] 타입스크립트와 자바스크립트의 관계 이해하기

### ISSUE THREAD

**Issue by kses1010** [code-itch/effective-typescript#2]

**Comment by kses1010** [comment]
> p8 작성된 프로그램이 타입 체클를 통과하더라도 여전히 런타임에 오류가 발생한다.

여기서 예시 코드가 다음과 같은데
```ts
const names = ['alice', 'bob'];
console.log(names[2].toUpperCase());

// TypeError: Cannot read properties of undefined (reading 'toUpperCase')
```
실제로 컴파일 단계에서는 알 수 없고 런타임을 돌려야 알 수 있습니다. 이와 반대로 정적 언어인 자바에서는
<img width="434" alt="image" src="https://github.com/code-itch/effective-typescript/assets/49144662/fbe05b15-2d41-4828-830d-d2bab7862347">
<img width="623" alt="image" src="https://github.com/code-itch/effective-typescript/assets/49144662/dce2b0a2-dfe2-455e-a8c4-5d539f33afd4">
위 사진처럼 해당 warning이라도 뜨는데 타입스크립트에서는 바로 확인하는 방법은 없을까요?

**Comment by kses1010** [comment]
> p8 Reason이나 Elm 같은 언어를 선택하는 것이 좋습니다.
여기서 Reason이나 Elm언어가 어떤 방식으로 정확성을 보여주는지 궁금해요

**Comment by han-kimm** [comment]
> 위 사진처럼 해당 warning이라도 뜨는데 타입스크립트에서는 바로 확인하는 방법은 없을까요?
: 타입스크립트는 배열의 경우, item의 자료형을 바탕으로 타입을 추론합니다. 따라서 개수까지 타입으로 한정하고 싶다면,
`const names = ['alice', 'bob'] as const` 에서 `as const`를 이용해서 readonly 타입로 만들어주어야 합니다.

이와 비슷한 용례로, `const obj = { a: "alice", b:"bob" }` 의 예시가 있는데요.
`obj.a` 의 타입 추론이 `string`이 됩니다.
만약 `"alice"`라는 특정값을 리터럴 타입으로 사용하고 싶다면
`const obj = { a: "alice", b:"bob" } as const`로 선언하세요.
