### ISSUE TITLE
[아이템 22] 타입 좁히기

### ISSUE THREAD

**Issue by gw-lim** [code-itch/effective-typescript#26]

**Comment by kses1010** [comment]
> p126 
```ts
function isInputElement(el: HTMLElement): el is HTMLInputElement {  
  return 'value' in el;  
}  
```
여기서의 value는 무엇을 의미하는걸까요? 꼭 value여야 하는지 궁금합니다.

**Comment by kses1010** [comment]
> p126
```ts
function getElementContent(el: HTMLElement) {
  if (el instanceof HTMLInputElement) {
    el;
    return el.value;
  }
  el;
  return el.textContent;
}
```
여기서 `isInputElement` 대신 instanceof로 사용하는것과 어떤 차이점이 있을까요?
`is` 라는 키워드가 활용이 많이 될까 궁금합니다. 아직까지는 `is` 키워드가 많이 낯설긴 하네요

**Comment by han-kimm** [comment]
> > p126
> 
> ```ts
> function isInputElement(el: HTMLElement): el is HTMLInputElement {  
>   return 'value' in el;  
> }  
> ```
> 
> 여기서의 value는 무엇을 의미하는걸까요? 꼭 value여야 하는지 궁금합니다.

@kses1010
input 태그만 갖는 속성(value)을 리턴값에서 in 연산자로 확인함으로서 true 불린값을 리턴하기 위함입니다.
`return 'placeholder' in el` 로 써도 됩니다!

**Comment by han-kimm** [comment]
> > p126
> 
> ```ts
> function getElementContent(el: HTMLElement) {
>   if (el instanceof HTMLInputElement) {
>     el;
>     return el.value;
>   }
>   el;
>   return el.textContent;
> }
> ```
> 
> 여기서 `isInputElement` 대신 instanceof로 사용하는것과 어떤 차이점이 있을까요? `is` 라는 키워드가 활용이 많이 될까 궁금합니다. 아직까지는 `is` 키워드가 많이 낯설긴 하네요

@kses1010 
자바스크립트에 존재하는 Prototype의 Instance인 경우에는 `instanceof` 연산자를 사용해도 됩니다.
하지만, 개발자가 정의한 타입 중 하나로 명시해야 한다면? 사용자 정의 타입 가드를 사용해야 합니다.
예를 들면 API로 받은 유저에 대한 데이터와, 메인 영역에 표시할 카드들의 데이터를 구분할 때 사용할 수 있겠죠?
```
function isCardData(data: UserData | CardData): data is UserData {
  return 'profileImageUrl' in data;
}
```

**Comment by han-kimm** [comment]
`is 연산자`는 타입체커에게 타입추론을 위한 문맥을 전달하는 역할을 합니다.
단언보다는 강도가 약한, 유니온 타입과 같이 여러 타입들 중에서 한 가지 경우의 수를 특정할 때 사용합니다.

**Comment by han-kimm** [comment]
------------
부가적으로 p.127의 예시에서,
배열의 `filter` 메소드는 앞의 배열이 어떤 타입을 가지고 있는 지만 확인하고, 실제 런타임에서의 배열 내 아이템의 타입을 확인하지 못합니다. ex) 모두 undefined가 될건지 string이 될건지 타입스크립트는 런타임을 하지 않아서 모름. 이 모든 경우의 수를 포괄하는 최대한 넓은 범위로 추론을 하는 것임. 따라서 `filter`로는 타입가드가 불가능합니다~
