### ISSUE TITLE
[아이템 3] 코드 생성과 타입이 관계없음을 이해하기

### ISSUE THREAD

**Issue by kses1010** [code-itch/effective-typescript#4]

**Comment by BeMatthewsong** [comment]
p20 에서 두 번째 불렛(타입스크립트가 컴파일하는 코드는 ~)이 한 번에 와닿지 않는데 추가적인 설명을 해주실 수 있을까요?

**Comment by Ssong-Q** [comment]
> p20 에서 두 번째 불렛(타입스크립트가 컴파일하는 코드는 ~)이 한 번에 와닿지 않는데 추가적인 설명을 해주실 수 있을까요?

https://poiemaweb.com/es6-generator
제너레이터 함수는 ES6에 도입되었고 이터러블을 생성하는 함수입니다.

```ts
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
    }
}
```

우리는 tsconfig에서 위와 같은 설정을 마주하는데, es5로 셋팅해놓으면 es5 버전 자바스크립트로 컴파일 해줍니다. 신버전을 원하면, es2016, esnext 이런 것도 입력이 가능합니다.
그래서 어느정도 호환성을 고려한다면 es5, commonjs가 국룰인데, 제너레이터나 bigint 타입 등을 쓰려면 esnext 등으로 버전을 올려줘야 합니다.

`"target": "es5"` 으로 두고 만약 제너레이터 함수를 컴파일 한다면? 타입스크립트 컴파일러는 컴파일을 위해 특정 헬퍼 코드를 추가한다고 합니다. **따라서, `"target": "es5"` 을 가져가며 호환성을 놓치 못하는 대신, 특정 헬퍼 코드로 인해 오버헤드가 증가한다는 말을 합니다.**
만약 런타임 환경과의 호환성을 포기하고, 성능에 초점을 맞춘 `"target": "esnext"`(네이티브 구현체)를 선택하면 컴파일러 성능은 빨라질 수 있지만, 일부 오래된 런타임 환경에서는 동작하지 않을 수도...?

**Comment by kses1010** [comment]
> p19 타입스크립트에서는 런타임 타입과 선언된 타입이 맞지 않을 수 있습니다.

여기에 안내한 코드가
```ts
interface LightApiResponse {
  lightSwitchValue: boolean;
}

async function setLight() {
  const response = await fetch('/light');
  const result: LightApiResponse = await response.json();
  setLightSwitch(result.lightSwitchValue);
}
```
인데 만약 이 코드를 제대로 방어하려면 어떻게 방어할 수 있을까요?

**Comment by han-kimm** [comment]
API 응답 구조를 알고 있다면?
``` js
  const response = await fetch('/light');
  const result = await response.json();
  if (typeof result.lightSwitchValue === "Boolean") {
    setLightSwitch(result.lightSwitchValue);
  }
 ```
API 응답을 콘솔로 확인하지 않고, 일단 응답에 있는 불린값을 쓰겠다는 의도라면 객체를 이터레이터로 만들어서 for ...of문을 수행할 수도 있겠네요. 다만, 의도하지 않는 불린값으로 함수를 호출할 수 있다는거~
  ``` ts
  const response = await fetch('/light');
  const result: LightApiResponse = await response.json();
  for (const key of Object.keys(result)) {
    if(key.includes("light") && typeof result[key] === "Boolean") {
      setLightSwtich(result[key]);
    }
  }
  ```

**Comment by kses1010** [comment]
방어코드를 짜게 되지만 결국엔 타입스크립트로는 해결을 못하네요 😭
