### ISSUE TITLE
[아이템 44] 타입 커버리지를 추적하여 타입 안전성 유지하기

### ISSUE THREAD

**Issue by han-kimm** [code-itch/effective-typescript#49]

**Comment by qooktree1** [comment]
서드파티 타입 선언을 통한 any 타입들은 따로 건드릴 수 있는 부분이 아니므로 따로 any 타입을 줄일 수 있는 방법은 없는 거라고 이해하면 될까요??

**Comment by han-kimm** [comment]
@qooktree1 
type Augmentation을 이용해야 합니다.
API, SDK 등과 같이 내부 구조를 모르는 경우에는 any를 사용할 수 있습니다.

**Comment by BeMatthewsong** [comment]
> Ambient Module 1: declare namespace를 이용하여 필요한 타입 선언을 그룹화하여 하나의 객체처럼 다루기.

위에서 말하는 namespace는 어떤 거고 언제 쓰는 게 좋나요?!
