### ISSUE TITLE
[아이템 4] 구조적 타이핑에 익숙해지기

### ISSUE THREAD

**Issue by kses1010** [code-itch/effective-typescript#5]

**Comment by Ssong-Q** [comment]
해당 아이템의 제목에서 구조적 타이핑을 언급하고 본문에서도 구조적 타이핑이란 단어가 많이 쓰이지만, 
덕 타이핑에 대해서만 초반에 설명 했을 뿐, 구조적 타이핑이 무엇인지는 명확히 설명이 잘 안되어 있는 것 같은데요..
(어렴풋이 덕 타이핑 == 구조적 타이핑 이라고 표면적인 이해만 되는 것 같습니다.)
혹시 구조적 타이핑이 어떤 의미인지 알려주실 수 있으실까요?

**Comment by qooktree1** [comment]
TypeScript는 런타임에 컴퓨터가 타입을 결정하는 덕 타이핑의 특징을 가진 JavaScript +  컴파일 시점에 타입을 검사하는 구조적 타이핑 이라고 할 수 있을 것 같습니다.

다시 말해, 구조적 타이핑은 컴파일 타임에 타입을 체크할 수 있다는 특징을 가지고 있습니다.

**Comment by Ssong-Q** [comment]
## 덕 타이핑과 구조적 타이핑 알아보다가 괜찮은 사이트가 있어서 퍼왔습니다.

[덕-타이핑과-구조적-타이핑](https://vallista.kr/%EB%8D%95-%ED%83%80%EC%9D%B4%ED%95%91%EA%B3%BC-%EA%B5%AC%EC%A1%B0%EC%A0%81-%ED%83%80%EC%9D%B4%ED%95%91/)

### 구조적 타입 시스템

생산성이 좋으면서도 타입의 장점을 가져가는 것
구조적 타이핑은 명목적 타이핑과 같은 명확한 상속 관계(A - B)를 지향하기보다 집합으로 포함한다는 개념을 지향

### **덕 타이핑과 구조적 타이핑의 차이**

덕 타이핑과 구조적 타이핑의 차이는 무엇인가?

1. 덕 타이핑은 런타임에 타입을 체크한다 (혹은 안할수도 있음)
2. 구조적 타이핑은 타입 시스템 기반에서 컴파일 타임(혹은 타입체커)에서 타입을 체크한다.
3. 즉, 둘 다 객체의 변수, 메소드 같은 필드를 기반으로 타입을 체크(혹은 안할수도)하지만 덕 타이핑은 동적 타이핑에서, 구조적 타이핑은 정적 타이핑에서 쓰인다
4. 덕 타이핑은 다형성 관점에서 주목해야하고, 구조적 타이핑은 타입 체킹 관점이다.
