### ISSUE TITLE
[아이템 45] devDependencies에 typescript와 @types 추가하기

### ISSUE THREAD

**Issue by han-kimm** [code-itch/effective-typescript#50]

**Comment by gw-lim** [comment]
> 런타임에 @types가 필요한 경우라면 별도의 작업이 필요하다.

여기서 런타임에 @types가 필요한 경우에 대한 예시가 있을까요?

**Comment by kses1010** [comment]
아이템 46에서 다룬다고 해서 확인해본 결과 보통 타입버전이 프로젝트와 맞지않을경우에 버전을 따로 맞출경우라고 생각하면 될 것 같습니다.
