### ISSUE TITLE
[아이템 47] 공개 API에 등장하는 모든 타입을 익스포트하기

### ISSUE THREAD

**Issue by han-kimm** [code-itch/effective-typescript#52]

**Comment by kses1010** [comment]
그나마 export해야하지 말아야할 대상은 무엇인가요?

**Comment by qooktree1** [comment]
저는 공개 메서드에서 사용되는 타입들 중에 직접적으로 접근할 필요가 없는 타입들은 export하지 않아도 된다고 생각합니다. 유틸리티 타입들로 접근이 가능하기 때문에 타입 접근하는데 불가능하지 않고, 바로 접근이 가능한 코드와 불가능한 코드를 나누어 사용자가 사용하는 데 있어서 예측 가능하고 가독성있는 코드가 된다고 생각합니다.
