### ISSUE TITLE
[아이템 49] 콜백에서 this에 대한 타입 제공하기

### ISSUE THREAD

**Issue by BeMatthewsong** [code-itch/effective-typescript#54]

**Comment by han-kimm** [comment]
아이템 49를 읽고 나서 든 의문,
그래서 this의 타입을 어떻게 명시한다는 거죠?

call(), apply()를 이용해서 this를 이용하는 건 알겠습니다.
화살표 함수의 경우에는 렉시컬 스코프로 this가 참조되니까,
예를 들어, 이벤트리스너를 호출하는 경우 콜백함수에서 this 바인딩이 안되기 때문에
callbackfn(this, e) 형식으로 쓰는건가요?
