### ISSUE TITLE
[아이템 50] 오버로딩 타입보다는 조건부 타입을 사용하기 

### ISSUE THREAD

**Issue by BeMatthewsong** [code-itch/effective-typescript#55]

**Comment by qooktree1** [comment]
250pg. 조건부 타입을 사용하는 해결책을 설명하는 부분에서

```tsx
function double<T extends number | string>(x:T): T extends string ? string : number;
function double(x: any) { return x + x };
```
코드를 보다가 만약 타입이 2개가 아니라 더 늘어나게 된다면 가독성이 떨어질 것 같다는 생각이 들었습니다.
만약 삼항연산자를 사용하지 않고 조건부 타입을 사용하는 방법이 있다면 예시를 보여주실 수 있을까요? 아니면 타입이 많다면 다른 함수로 만드는 방법이 좋을까요??
