### ISSUE TITLE
[아이템 52] 테스팅 타입의 함정에 주의하기

### ISSUE THREAD

**Issue by BeMatthewsong** [code-itch/effective-typescript#57]

**Comment by han-kimm** [comment]
책 쓰신 분이 남겨놓은 함정이신거 같아요
이해가 어려운 챕터네요;;

**Comment by kses1010** [comment]
https://www.totaltypescript.com/how-to-test-your-types
여기 블로그가 재밌는 결론을 지었습니다.
> Those are three ways that you should be thinking about testing your types. It's worth noting that for application development, you're rarely going to be in a position where testing your types will be worth it.

애플리케이션 개발의 경우 유형을 테스트할 가치가 있는 위치에 있는 경우가 거의 없다는 점은 주목할 가치가 있습니다.
실무에서는 굳이 타입까지도 테스팅은 하지 않는듯 합니다. 그나마 하더라도 Vitest 라이브러리를 활용한다는 군요
