### ISSUE TITLE
[아이템 5] any 타입 지양하기

### ISSUE THREAD

**Issue by kses1010** [code-itch/effective-typescript#6]

**Comment by BeMatthewsong** [comment]
> p31 마지막에서 세 번째 문장에 '어쩔 수 없이 any를 써야만 하는 상황도 있습니다.' 

저희 멘토님께서 any를 쓰지 않는 방향으로 코드를 짤 수 있다고 하셨는데, 정말 불가피하게 any를 써야 하는 상황도 올 수 있을 텐데 그런 상황은 무슨 상황인지 간단한 예시라도 알려주시면 좋을 것 같습니다.

**Comment by kses1010** [comment]
@BeMatthewsong 

보통 외부 라이브러리 사용할 때 any 타입으로 사용합니다. 외부 라이브러리/API 경우 데이터 타입이 저희가 제어할 수 없을 수 있거든요.
만약 npm에 등록된 라이브러리가 타입스크립트를 지원하기가 애매할 경우 일단 외부라이브러리/API를 통해 가져온 데이터는 any로 받고 그 데이터를 타입을 걸어 놓으면 될 듯 합니다.

```ts
const externalLibrary: any;

interface ExternalData {
  name: string,
  age: string
}
const data: ExternalData = { ... externalLibrary };
```
